service: demo-node

# Using 4 spaces for indentation

frameworkVersion: '3'
configValidationMode: error
useDotenv: true

provider:
    name: aws
    runtime: nodejs18.x
    stage: ${opt:stage, 'local'}
    region: ap-northeast-1
    timeout: 30
    memorySize: 512 #Default Lambda Memory Size
    apiGateway:
        apiKeys:
            - ${opt:stage, 'local'}-demo-node-service-apikey

package:
    patterns: ${file(package-patterns.yml)}
    excludeDevDependencies: true

custom:
    stage: ${opt:stage, 'local'}
    localstack:
        stages: [local]
        debug: true
        host: http://localhost
        edgePort: 4566
        lambda:
            mountCode: false
    serverless-offline:
        host: '0.0.0.0'
        httpPort: 3000
        noAuth: true

plugins:
    - serverless-localstack
    - serverless-offline

functions:
    - ${file(serverless-dynamic-functions.js)}

resources:
    Resources: ${file(serverless-dynamic-resources.js)}
