service: demo-node

# Using 4 spaces for indentation

frameworkVersion: '3'
configValidationMode: error
useDotenv: true

provider:
    name: aws
    runtime: nodejs18.x
    stage: ${opt:stage, 'local'}
    region: ap-northeast-1
    timeout: 30
    memorySize: 512 #Default Lambda Memory Size

custom:
    stage: ${opt:stage, 'local'}
    localstack:
        stages: [local]
        debug: true
        host: http://localhost
        edgePort: 4566
        lambda:
            mountCode: false
    esbuild:
        minify: true

plugins:
    - serverless-localstack
    - serverless-esbuild

functions:
    - ${file(serverless-dynamic-functions.js)}

resources:
    Resources: ${file(serverless-dynamic-resources.js)}
