S3BUCKETSTORAGE:
    Type: AWS::S3::Bucket
    Properties:
        BucketName: demo-node-${opt:stage}
        PublicAccessBlockConfiguration:
            BlockPublicAcls: true
            BlockPublicPolicy: true
            IgnorePublicAcls: true
            RestrictPublicBuckets: true

S3EXECUTIONROLE:
    Type: AWS::IAM::Role
    Properties:
        AssumeRolePolicyDocument:
            Statement:
                - Effect: Allow
                  Principal:
                      Service:
                          - lambda.amazonaws.com
                  Action:
                      - sts:AssumeRole

        Policies:
            - PolicyName: AccessS3Policy
              PolicyDocument:
                  Version: '2012-10-17'
                  Statement:
                      - Effect: 'Allow'
                        Action:
                            - s3:ListBucket
                        Resource:
                            - Fn::Join:
                                  - '/'
                                  - - { 'Fn::GetAtt': [S3BUCKETSTORAGE, Arn] }
                      - Effect: 'Allow'
                        Action:
                            - s3:GetObject
                            - s3:ListBucket
                            - s3:PutObject
                            - s3:ListObject
                            - s3:DeleteObject
                        Resource:
                            - Fn::Join:
                                  - '/'
                                  - - { 'Fn::GetAtt': [S3BUCKETSTORAGE, Arn] }
                                    - '*'
